galaxy_info:
  author: sanicek
  description: Fedora Kitty terminal setup.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - fedora
    - terminal
    - kitty
dependencies: []
