galaxy_info:
  author: sanicek
  description: Fedora power-management preferences.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - fedora
    - power
dependencies: []
