- name: Install Kitty packages
  community.general.pacman:
    name:
      - kitty
      - kitty-terminfo
    state: present

- name: Ensure Kitty configuration directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.config/kitty"
    state: directory
    mode: "0755"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  become: false

- name: Ensure user application launcher directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.local/share/applications"
    state: directory
    mode: "0755"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  become: false

- name: Copy custom Kitty configuration
  ansible.builtin.copy:
    src: kitty/kitty.conf
    dest: "{{ user_home }}/.config/kitty/kitty.conf"
    mode: "0644"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  become: false

- name: Configure Kitty launcher to start maximized
  ansible.builtin.copy:
    dest: "{{ user_home }}/.local/share/applications/kitty.desktop"
    content: |
      [Desktop Entry]
      Type=Application
      Name=kitty
      GenericName=Terminal Emulator
      Comment=Fast, feature-rich, GPU based terminal
      Exec=kitty --start-as=maximized
      Icon=kitty
      Terminal=false
      Categories=System;TerminalEmulator;
      StartupWMClass=kitty
    mode: "0644"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  become: false
