# https://sw.kovidgoyal.net/kitty/conf

font_family      Cascadia Mono

font_size 16.0

disable_ligatures always

copy_on_select yes
mouse_map right press grabbed,ungrabbed paste_from_selection

enable_audio_bell no

remember_window_size  no
initial_window_width  640
initial_window_height 400

hide_window_decorations no

tab_bar_style powerline

tab_powerline_style slanted

editor vi

update_check_interval 0

shell_integration disabled

# Flexoki Dark
# https://github.com/kepano/flexoki/blob/main/kitty/flexoki_dark.conf
foreground              #CECDC3
background              #100F0F
selection_foreground    #CECDC3
selection_background    #403E3C

cursor                  #CECDC3
cursor_text_color       #100F0F

active_border_color     #AF3029
inactive_border_color   #403E3C

active_tab_foreground   #CECDC3
active_tab_background   #403E3C
inactive_tab_foreground #878580
inactive_tab_background #282726

color0  #100F0F
color8  #6F6E69
color1  #AF3029
color9  #D14D41
color2  #66800B
color10 #879A39
color3  #AD8301
color11 #D0A215
color4  #205EA6
color12 #4385BE
color5  #A02F6F
color13 #CE5D97
color6  #24837B
color14 #3AA99F
color7  #878580
color15 #CECDC3
