- name: Install git
  community.general.pacman:
    name: git
    state: present

- name: Clone bash-git-prompt repository
  ansible.builtin.git:
    repo: https://github.com/magicmonty/bash-git-prompt.git
    dest: /usr/local/share/bash-git-prompt
    clone: true
    update: true

- name: Add bash-git-prompt to user's bashrc
  ansible.builtin.blockinfile:
    path: "{{ user_home }}/.bashrc"
    block: |
      if [ -f "/usr/local/share/bash-git-prompt/gitprompt.sh" ]; then

        GIT_PROMPT_ONLY_IN_REPO=0
        GIT_PROMPT_THEME=BlackOrWhite
        GIT_PROMPT_BLACK_OR_WHITE_THEME_PS1_COLOR=white
        GIT_PROMPT_BLACK_OR_WHITE_THEME_STYLE=bubbles
        GIT_PROMPT_BLACK_OR_WHITE_THEME_VISIBLE_SECTIONS=user_and_hostname,path,last_command_state,time

        source /usr/local/share/bash-git-prompt/gitprompt.sh

        function set_title {
          local DIR=$(pwd | sed "s|^$HOME|~|")
          if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
            echo -ne "\033]0;${USER}@${HOSTNAME}:${DIR}\007"
          else
            echo -ne "\033]0;${DIR}\007"
          fi
        }

        add_to_end_of_prompt_command set_title

      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK bash-git-prompt"
    create: true
    mode: "0644"
  become: false

- name: Add bash-git-prompt to Arch system bashrc
  ansible.builtin.blockinfile:
    path: /etc/bash.bashrc
    block: |
      if [ -f "/usr/local/share/bash-git-prompt/gitprompt.sh" ]; then

        GIT_PROMPT_ONLY_IN_REPO=0
        GIT_PROMPT_THEME=BlackOrWhite
        GIT_PROMPT_BLACK_OR_WHITE_THEME_PS1_COLOR=white
        GIT_PROMPT_BLACK_OR_WHITE_THEME_STYLE=bubbles
        GIT_PROMPT_BLACK_OR_WHITE_THEME_VISIBLE_SECTIONS=user_and_hostname,path,last_command_state,time

        source /usr/local/share/bash-git-prompt/gitprompt.sh

        function set_title {
          local DIR=$(pwd | sed "s|^$HOME|~|")
          if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
            echo -ne "\033]0;${USER}@${HOSTNAME}:${DIR}\007"
          else
            echo -ne "\033]0;${DIR}\007"
          fi
        }

        add_to_end_of_prompt_command set_title

      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK bash-git-prompt"
    create: true
    mode: "0644"
