galaxy_info:
  author: sanicek
  description: Common Fedora packages.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - fedora
    - packages
dependencies: []
