galaxy_info:
  author: sanicek
  description: Arch Linux kubectl setup.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - arch
    - archlinux
    - kubectl
    - kubernetes
dependencies: []
