galaxy_info:
  author: sanicek
  description: UFW firewall setup.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - firewall
    - ufw
    - server
dependencies: []
