galaxy_info:
  author: sanicek
  description: Arch Linux fzf setup using native packages.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - arch
    - archlinux
    - shell
    - fzf
dependencies: []
