- name: CHROME - Set Chrome repository details for openSUSE
  set_fact:
    chrome_repo_file: "/etc/zypp/repos.d/google-chrome.repo"
    chrome_repo_content: |
      [google-chrome]
      name=Google Chrome
      baseurl=https://dl.google.com/linux/chrome/rpm/stable/x86_64
      enabled=1
      gpgcheck=1
  when: "'openSUSE' in ansible_distribution"

- name: CHROME - Set Chrome repository details for Fedora
  set_fact:
    chrome_repo_file: "/etc/yum.repos.d/google-chrome.repo"
    chrome_repo_content: |
      [google-chrome]
      name=google-chrome - 64-bit
      baseurl=https://dl.google.com/linux/chrome/rpm/stable/x86_64
      enabled=1
      gpgcheck=1
  when: ansible_distribution == "Fedora"
  
- name: CHROME - Add Google Chrome repository key
  rpm_key:
    state: present
    key: https://dl.google.com/linux/linux_signing_key.pub

- name: CHROME - Add Google Chrome repository
  copy:
    dest: "{{ chrome_repo_file }}"
    content: "{{ chrome_repo_content }}"
  notify: Refresh repositories
  when: chrome_repo_file is defined

- name: CHROME - Install Google Chrome
  package:
    name: google-chrome-stable
    state: present
  when: package_manager is defined