- name: KITTY - Install packages
  package:
    name: 
      - kitty
      - kitty-terminfo
    state: present
  when: package_manager is defined

#this does it for the user running ansible
- name: KITTY - Ensure Kitty configuration directory exists
  file:
    path: "{{ user_home }}/.config/kitty"
    state: directory
    mode: '0755'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  become: no
    
- name: KITTY - Copy custom Kitty configuration
  copy:
    src: ../files/kitty/kitty.conf
    dest: "{{ user_home }}/.config/kitty/kitty.conf"
    mode: '0644'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  become: no