- name: POWER SETTINGS - Disable hibernation
  command: systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target suspend-then-hibernate.target

- name: POWER SETTINGS - Disable lock screen
  command: gsettings set org.gnome.desktop.screensaver lock-enabled false

- name: POWER SETTINGS - Disable automatic suspend on AC power
  command: gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'

- name: POWER SETTINGS - Disable automatic suspend on battery power
  command: gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing'

- name: POWER SETTINGS - Set idle-delay to never (disables screensaver activation)
  command: gsettings set org.gnome.desktop.session idle-delay 0

- name: POWER SETTINGS - Set blank screen to never
  command: gsettings set org.gnome.desktop.screensaver idle-activation-enabled false

- name: POWER SETTINGS - Disable lock on suspend
  command: gsettings set org.gnome.desktop.lockdown disable-lock-screen true

- name: POWER SETTINGS - Disable automatic screen lock
  command: gsettings set org.gnome.desktop.screensaver idle-activation-enabled false

#- name: POWER SETTINGS - Disable screen blanking in gdm
#  command: gsettings set org.gnome.settings-daemon.plugins.power sleep-display-ac false

- name: POWER SETTINGS - Disable screen lock after resume
  command: gsettings set org.gnome.desktop.screensaver lock-delay 0

- name: POWER SETTINGS - Update logind.conf for complete power management control
  block:
    - name: POWER SETTINGS - Ensure /etc/systemd/logind.conf exists
      file:
        path: /etc/systemd/logind.conf
        state: touch

    - name: POWER SETTINGS - Configure logind.conf
      lineinfile:
        path: /etc/systemd/logind.conf
        regexp: '^#?(HandleSuspendKey|HandleLidSwitch|HandleLidSwitchDocked|HandleHibernateKey|HandleSleepKey|IdleAction)='
        line: '\1=ignore'
        create: yes
      with_items:
        - 'HandleSuspendKey=ignore'
        - 'HandleLidSwitch=ignore'
        - 'HandleLidSwitchDocked=ignore'
        - 'HandleHibernateKey=ignore'
        - 'HandleSleepKey=ignore'
        - 'IdleAction=ignore'
#    - name: POWER SETTINGS - Restart logind service to apply changes
#        systemd:
#        iname: systemd-logind
#        state: restarted
