arch_opencode_package: opencode
arch_opencode_bun_package: bun
arch_opencode_install_bun: false

arch_opencode_profile: ""

arch_opencode_config_dir: "{{ user_home }}/.config/opencode"
arch_opencode_managed_files:
  - opencode.jsonc
  - tui.jsonc

arch_opencode_omo_slim_managed_files:
  - oh-my-opencode-slim.json

arch_opencode_enable_background_subagents: false
arch_opencode_shell_env: {}
arch_opencode_shell_env_path: "{{ user_home }}/.bashrc"
