# Molecule managed
FROM {{ item.image }}

RUN pacman -Syu --noconfirm \
    && pacman -S --noconfirm bash curl git gzip python sudo shadow tar \
    && pacman -Scc --noconfirm

RUN useradd -m -s /bin/bash molecule \
    && mkdir -p /etc/sudoers.d \
    && printf 'molecule ALL=(ALL) NOPASSWD: ALL\n' > /etc/sudoers.d/molecule \
    && chmod 0440 /etc/sudoers.d/molecule
