namespace: sanicek
name: server
version: 0.1.0
readme: README.md
authors:
  - sanicek
description: Server configuration-as-code Ansible collection.
license:
  - MIT
tags:
  - arch
  - archlinux
  - linux
  - server
dependencies:
  community.general: ">=8.0.0"
